# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161103_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competitors',
            new_name='Competitor',
        ),
    ]
