# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161103_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='company_logo',
            new_name='Competitor_Logo',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='company_category',
            new_name='Competitor_Name',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='company_crunchbase',
            new_name='Competitor_Website',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='company_facebook',
            new_name='Crunchbase',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='company_linkedin',
            new_name='Facebook',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='company_name',
            new_name='LinkedIn',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='company_notes',
            new_name='Notes',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='company_similarweb',
            new_name='Similarweb',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='company_twitter',
            new_name='Twitter',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='company_website',
            new_name='cCategory',
        ),
    ]
