# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161103_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='Category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='Crunchbase',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='Facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='LinkedIn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='Similarweb',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='Twitter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
